-- TOTALLYLEGALMARKET Supabase setup
-- Run this entire file in Supabase Dashboard -> SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.showcases (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  description text default '',
  video_path text not null,
  created_at timestamptz not null default now(),
  approved boolean not null default true
);

alter table public.profiles enable row level security;
alter table public.showcases enable row level security;

drop policy if exists "public profiles readable" on public.profiles;
create policy "public profiles readable" on public.profiles for select using (true);

drop policy if exists "users can edit own profile" on public.profiles;
create policy "users can edit own profile" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "showcases readable when approved" on public.showcases;
create policy "showcases readable when approved" on public.showcases for select using (approved = true or auth.uid() = user_id);

drop policy if exists "users can create own showcases" on public.showcases;
create policy "users can create own showcases" on public.showcases for insert with check (auth.uid() = user_id);

drop policy if exists "users can edit own showcases" on public.showcases;
create policy "users can edit own showcases" on public.showcases for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "users can delete own showcases" on public.showcases;
create policy "users can delete own showcases" on public.showcases for delete using (auth.uid() = user_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, username)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'username', split_part(new.email, '@', 1)))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Public video bucket.
insert into storage.buckets (id, name, public)
values ('showcase-videos', 'showcase-videos', true)
on conflict (id) do update set public = true;

drop policy if exists "showcase videos are public" on storage.objects;
create policy "showcase videos are public" on storage.objects for select using (bucket_id = 'showcase-videos');

drop policy if exists "users upload showcase videos to own folder" on storage.objects;
create policy "users upload showcase videos to own folder" on storage.objects for insert to authenticated with check (bucket_id = 'showcase-videos' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "users update own showcase videos" on storage.objects;
create policy "users update own showcase videos" on storage.objects for update to authenticated using (bucket_id = 'showcase-videos' and owner_id = auth.uid()::text);

drop policy if exists "users delete own showcase videos" on storage.objects;
create policy "users delete own showcase videos" on storage.objects for delete to authenticated using (bucket_id = 'showcase-videos' and owner_id = auth.uid()::text);
